server:
 port: 9199
spring:
   datasource:
      url: jdbc:mysql://localhost:3306/chatmessage?createDatabaseIfNotExist=true
      username: root
      password: Micro@123
      driver-classs-name: com.mysql.jdbc.Driver     
   jpa:
     hibernate:
      naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create   